### ISSUE TITLE
Re-jig of heatmap

### ISSUE THREAD

**Issue by hyanwong** [awohns/tsdate_paper#8]
It would be good to extend the Samaritan histogram to the left. I think this can be done by reversing the Y axis (which is what I do in the interactive plot anyway, to make room for the heatmap legend). The first mock-up below shows this - it has the additional advantage that the X axes on the histograms are all lined up, so we should only need one X axis label.

The slight disadvantage is that it makes it look like Europeans are at the "top" of the tree! We could get around this by displaying the labels etc at the top of the plot (rough mockup 2) - this has the additional advantage that the African / non-African plot, which I guess we would talk about first, is at the top, and the longest X scale for times (for the samaritan histogram) is at the bottom.

MOCK UP 1
<img width="723" alt="Screenshot 2020-11-09 at 10 47 06" src="https://user-images.githubusercontent.com/4699014/98531931-ec407800-2278-11eb-8cf0-ccb85dd672b4.png">

MOCK UP 2
![Screenshot 2020-11-09 at 11 26 07](https://user-images.githubusercontent.com/4699014/98535647-5f002200-227e-11eb-9431-2a195ee7d38b.png)

**Comment by hyanwong** [comment]
Also, I wonder if we can gain some space and reduce clutter by overlaying the black SGDP etc squares on top of the location colours, like this:

![Screenshot 2020-11-09 at 11 56 29](https://user-images.githubusercontent.com/4699014/98538401-9e307200-2282-11eb-8dcc-1d071afbc9a0.png)

**Comment by hyanwong** [comment]
Finally (and I'll stop now!) there's space to put the heatmap legend and the region colours in the empty spaces in the rest of the plot. I think this is definitely worth considering, as it will allow the heatmap itself to be bigger. In the example below I've aligned the mean TMRCA legend with the scale on the histograms, but perhaps that's a bit too extreme, I've also had a play with the histogram lines, making the histograms themselves grey so we can use the background colour to see where they come from. See what you think - we can talk about it online.

![Screenshot 2020-11-09 at 12 53 15](https://user-images.githubusercontent.com/4699014/98543531-8b21a000-228a-11eb-82d8-638f2e4e6390.png)

**Comment by awohns** [comment]
Here's my version of your suggestions. I haven't pulled out the data for the lower end of the histogram, I thought I might check in with you to see how to do that.

[Uploading figure3_clustered_tmrca_flipped.pdf…]()

**Comment by awohns** [comment]
Here are the changes I coded up to the figure based on your suggestions. I haven't been able to get the lower end of the histogram, I thought I'd check with you to see how that can best be done
![image](https://user-images.githubusercontent.com/10664424/98628982-c5815080-230f-11eb-9548-8b34f610b211.png)

**Comment by awohns** [comment]
Here are the changes I coded up to the figure based on your suggestions. I haven't been able to get the lower end of the histogram, I thought I'd check with you to see how that can best be done. 
I'll also remove the West Eurasia and South Asia labels and merge them with the others of the same color
![image](https://user-images.githubusercontent.com/10664424/98630163-6cff8280-2312-11eb-81cd-52288a50d5b7.png)

**Comment by hyanwong** [comment]
Great @awohns - I'll get on with histogram (FYI, the data is on holly in `/home/yan/tsdate_paper/all-data/merged_hgdp_1kg_sgdp_high_cov_ancients_chr20.dated.binned.historic.20nodes.tmrcas_RAW.npz`).

Two things for improvement in your replot: could you make the legends within the histograms in larger font? And if we are not moving the "barcode" thing at the very top the plot to overlay the colours, then I think it should be between the names and the heatmap, not above the names.

**Comment by hyanwong** [comment]
So there's a slight problem with the Samaritan plot, because there is a massive peak at the start, at 1e-6 generations. We can completely justifiably put this at 1 generation (1st plot below). But the problem is that there isn't enough room in the current layout to extend the plot all the way back to 1 generation - probably only to 10 generations. We could merge generations 1-20 into a single bin, and cut off the plot at 10, but this would make the lowest bin appear very small, because most is missing (2nd plot below). Or we could merge everything below 10 generations into a single bin at 10 generations (3rd plot below), and explain in the caption. Or, probably my preferred option, we could merge everything below (say) 20 into a bin of 20 or less and explain (4th plot).

Preferences @awohns ?

![image](https://user-images.githubusercontent.com/4699014/98667207-0431fd80-2346-11eb-82e2-0b34d8664831.png)

Rough code to generate as follows:

```
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

raw_arrays = np.load("all-data/merged_hgdp_1kg_sgdp_high_cov_ancients_chr20.dated.binned.historic.20nodes.tmrcas_RAW.npz")
hist_data = np.load("all-data/merged_hgdp_1kg_sgdp_high_cov_ancients_chr20.dated.binned.historic.20nodes.tmrcas.npz")
log_unique_times = raw_arrays['arr_0']
raw_data = raw_arrays['arr_1']
combos = hist_data['combos']
samaritan = np.where(
    np.any(combos == ['Samaritan (SGDP)', 'Samaritan (SGDP)'], axis=1))[0]
samaritan_samaritan = np.where(
    np.all(combos == ['Samaritan (SGDP)', 'Samaritan (SGDP)'], axis=1))[0]
samaritan_other = samaritan[np.logical_not(np.in1d(samaritan, samaritan_samaritan))]

hist_min_gens = 1e-6
data = raw_data[samaritan_samaritan,:]
av_weight = np.mean(data, axis=0)
keep = (av_weight != 0)

fig, axs = plt.subplots(4, figsize=(15, 12))
# everything under 1 generation get put at 1
log_gens = np.where(np.exp(log_unique_times)< 1, np.log(1), log_unique_times)
height, bins = np.histogram(
        log_gens[keep],
        weights=av_weight[keep],
        bins=hist_nbins,
        density=True)
axs[0].semilogx(np.exp(bins), np.insert(height, 0, height[0]), '-', drawstyle='steps')

# Merge bottom bins up to 20 gens
bins = np.concatenate((bins[:1], bins[np.exp(bins)>=20]))
height, bins = np.histogram(
        log_gens[keep],
        weights=av_weight[keep],
        bins=bins,
        density=True)
axs[1].semilogx(np.exp(bins), np.insert(height, 0, height[0]), '-', drawstyle='steps')
axs[1].set_xlim(10)

# everything under 10 generations get put at 10
log_gens = np.where(np.exp(log_unique_times)< 10, np.log(10), log_unique_times)
height, bins = np.histogram(
        log_gens[keep],
        weights=av_weight[keep],
        bins=hist_nbins,
        density=True)
axs[2].semilogx(np.exp(bins), np.insert(height, 0, height[0]), '-', drawstyle='steps')
axs[2].set_xlim(10)

# Merge bottom bins up to 20 gens
_, bins = np.histogram(
        log_gens[keep],
        weights=av_weight[keep],
        bins=hist_nbins,
        density=True)
bins = np.concatenate((bins[:1], bins[np.exp(bins)>=20]))
height, bins = np.histogram(
        log_gens[keep],
        weights=av_weight[keep],
        bins=bins,
        density=True)

axs[3].semilogx(np.exp(bins), np.insert(height, 0, height[0]), '-', drawstyle='steps')
axs[3].set_xlim(10)
```

**Comment by awohns** [comment]
Looks good @hyanwong: I think I prefer the fourth option as well

**Comment by hyanwong** [comment]
OK, great. Where's the code to produce the heatmap + histogram plot? I can add this to that, I guess.

**Comment by awohns** [comment]
I'll PR it now

**Comment by hyanwong** [comment]
I just realised that if we put all node time estimates < 1 at time 1, it brings up the Samaritan geometric mean tMRCA to 1111.06 rather than 74 generations. We should probably do that.

**Comment by awohns** [comment]
Taking a bit of time to get all the code from notebook into github (I'm including the ancient descent stuff too), will hopefully PR it in 2 hours or so

**Comment by hyanwong** [comment]
No hurry.

**Comment by hyanwong** [comment]
New TMRCA file to use as the source of the heatmap in my home directory on holly at `tsdate_paper/all-data/merged_hgdp_1kg_sgdp_high_cov_ancients_chr20.dated.binned.historic.20nodes.tmrcas.csv`.

**Comment by awohns** [comment]
See #9 for the inset histogram code. It's in `src/plot.py` and is called: `InsetTmrcaHistograms`

**Comment by hyanwong** [comment]
How's this, @awohns :

![inset_tmrca_histograms](https://user-images.githubusercontent.com/4699014/99377193-d3117a00-28bd-11eb-927e-c023db7284d3.png)

**Comment by awohns** [comment]
Looks great to me! The Denisovan/Papuan +Australian pattern is very subtle, but I guess it was always like that. Perhaps we should be consistent in our use of a comma instead of a plus in the legend where we write "Papuans, Australians"

**Comment by hyanwong** [comment]
Yes. I think it's stronger if we just plot Bougainville?

If this is generally OK, do you want to merge #13 ?

**Comment by awohns** [comment]
I decided to use the other Papuan/Australian populations because if we just did Bougainville/Denisovan, all other moderns/Denisovan, the other populations got folded into the latter comparison.

**Comment by hyanwong** [comment]
Yeah, but they will probably be drowned out by everything else.

**Comment by awohns** [comment]
Sorry, closed by mistake.
I tried both... I recall this looked slightly better, but we can try Bougainville if you'd like

**Comment by hyanwong** [comment]
I think this can be closed
